### ISSUE TITLE
Translate subcategories names and other main texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-it#8]
- Arduino Reference
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- functions
- For controlling the Arduino board and performing computations.
- Digital I/O
- Analog I/O
- Zero, Due & MKR Family
- Advanced I/O
- Time
- Math
- Trigonometry
- Characters
- Random Numbers
- Bits and Bytes
- External Interrupts
- Interrupts
- Communication
- Serial
- Stream
- USB
- Keyboard
- Mouse
- variables
- Arduino data types and constants.
- Constants
- Conversion
- Data Types
- Variable Scope & Qualifiers
- Utilities
- structure
- The elements of Arduino (C++) code.
- Sketch
- Control Structure
- Further Syntax
- Arithmetic Operators
- Comparison Operators
- Boolean Operators
- Pointer Access Operators
- Bitwise Operators
- Compound Operators

**Comment by qub1750ul** [comment]
In which file has this to be done ?

**Comment by smellai** [comment]
If you want you can write the translations directly here in a comment, thanks

**Comment by qub1750ul** [comment]
- Documentazione di riferimento di Arduino
- La documentazione di riferimento del linguaggio di programmazione di Arduino, organizzata in Funzioni, Variabili e Costanti, e parole chiave di Struttura.
- funzioni
- Per controllare la scheda Arduino e fare calcoli.
- I/O Digitale
- I/O Analogico
- Zero, Due & Famiglia MKR
- I/O Avanzato
- Tempo 
- Matematica
- Trigonometria
- Caratteri
- Numeri Casuali
- Bit e Byte
- Interrupt Esterni
- Interrupt
- Comunicazione
- Seriale
- Stream
- USB
- Tastiera
- Mouse
- variabili
- Tipi di dato e costanti di Arduino.
- Costanti
- Conversione
- Tipi di dato
- Visibilità delle delle variabili & Qualificatori
- Utilità
- struttura
- Gli elementi del codice Arduino ( C++ ).
- Sketch
- Struttura di Controllo
- Sintassi Aggiuntiva
- Operatori Aritmetici
- Operatori di Comparazione
- Operatori Booleani
- Operatori di Accesso a Puntatore
- Operatori a bit singolo
- Operatori Composti
