### ISSUE TITLE
Site translations

### ISSUE THREAD

**Issue by smellai** [arduino/reference-it#9]
- id: pageTitle
  translation: Language Reference

- id: pageDescription
  translation: "Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions."

- id: license
  translation: "The Arduino Reference text is licensed under a <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 License</a>."

- id: githubLink
  translation: "Find anything that can be improved? <a href=\"https://github.com/arduino/reference-en\" target=\"_blank\" rel=\"noopener\">Suggest corrections and new documentation via GitHub.</a>"

- id: tutorialLink
  translation: "Doubts on how to use Github? Learn everything you need to know in <a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">this tutorial</a>."

**Comment by qub1750ul** [comment]
In which file has this to be done ?

**Comment by smellai** [comment]
You can write directly here thanks! Those strings are not in the public repo

**Comment by qub1750ul** [comment]
id: pageTitle
translation: Documentazione di riferimento del linguaggio

id: pageDescription
translation: "Il linguaggio di programmazione di Arduino può essere diviso in tre parti principali: struttura, valori ( variabili e costanti ), e funzioni."

id: license
translation: "Il testo della Documentazione di riferimento di Arduino e' rilasciato sotto una <a href="https://creativecommons.org/licenses/by-sa/3.0/\" target="_blank" rel="noopener"> licenza Creative Commons Attribution-Share Alike 3.0 ."

id: githubLink
translation: "Trovato qualcosa che puo' essere migliorato ? <a href="https://github.com/arduino/reference-it\" target="_blank" rel="noopener">Suggerisci correzioni e nuova documentazione via GitHub."

id: tutorialLink
translation: "Dubbi su cone usare GitHub? Impara tutto quello che devi sapere in <a href="https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target="_blank" rel="noopener">questo tutorial."
